# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Case2-MobileAppPromo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Case2-MobileAppPromo
#  pod 'Alamofire', '~> 4.0'
#  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end

