# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Case4-MobileAppPushNotif' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Case4-MobileAppPushNotif
  pod 'SnapKit', '~> 5.0.1'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
