# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Case3-MobileAppPortfolio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Case3-MobileAppPortfolio
  pod 'Charts'
  pod 'SnapKit', '~> 5.0.0'

end
